#Teste para aleatorizar um nome para uma criança
import random
sx = str(input('Qual o sexo do bebê? '))[0].upper()
if sx == 'M':
#Lista de nomes masculinos que serão randomizados.
    m1 = ['Arthur Gabriel','João Vitor','Arthur Miguel','Luiz Felipe','Carlos Eduardo','Luiz Gustavo','Davi Luiz','Luiz Henrique','David Lucas','Davi Miguel','Enzo Gabriel','LuizOtávio','Enzo Miguel','Lucas Gabriel','João Gabriel','Pedro Henrique','João Guilherme','Pedro Lucas','João Lucas','Pedro Miguel','João Miguel','Vitor Hugo','João Pedro','Miguel', 'Davi', 'Gabriel', 'Arthur', 'Lucas', 'Matheus', 'Pedro', 'Guilherme','Alexandre','Eduardo','Henrique','Murilo','Theo','André','Enrico','Henry','Nathan','Thiago','Antônio','Enzo','Ian','Otávio','Thomas','Augusto','Erick','Isaac','Pietro','Vicente','Breno','Felipe','João','Rafael','Vinícius','Bruno','Fernando','Kaique','Raul','Vitor','Caio','Francisco','Leonardo','Rian','Yago','Cauã','Frederico','Luan','Ricardo','Ygor','Daniel','Guilherme','Lucas','Rodrigo','Yuri','Danilo','Gustavo','Mathias','Samuel']
    print('O nome masculino escolhido foi \033[4;34m{}\033[m.'.format(random.choice(m1)))
elif sx == 'F':
#Lista de nomes femininos que serâo randomizados.
    f1 = ['Coralina', 'Martina', 'Adele', 'Ayla', 'Dora', 'Agnes', 'Julieta', 'Serena', 'Lia', 'Mia', 'Allana', 'Branca', 'Estrela', 'Linda', 'Micaela', 'Felipa', 'Naomi', 'Amora', 'Celina', 'Luna', 'Violeta', 'Analu', 'Charlote', 'Pérola', 'Angelina', 'Pietra','Ana Beatriz', 'Maria Eduarda', 'Ana Cecília', 'Maria Fernanda', 'Ana Clara', 'Maria Flor', 'Ana Júlia', 'Maria Helena', 'Ana Laura', 'Maria Íris', 'Ana Lívia', 'Maria Júlia', 'Ana Luiza', 'Maria Laura', 'Ana Sofia', 'Maria Luíza', 'Ana Vitória', 'Maria Sophia', 'Maria Alice', 'Maria Valentina', 'Maria Cecília', 'Maria Vitória', 'Maria Clara','Agatha', 'Camila', 'Esther', 'Isis', 'Maitê', 'Natália', 'Alícia', 'Carolina', 'Fernanda', 'Joana', 'Malu', 'Nicole', 'Amanda', 'Catarina', 'Gabriela', 'Laís', 'Maria', 'Olívia', 'Ana', 'Cecília', 'Gabrielly', 'Lara', 'Marian', 'Pietra', 'Antonela', 'Clara', 'Giovana', 'Larissa', 'Mariana', 'Rafaela', 'Aurora', 'Clarice', 'Júlia', 'Marina', 'Rebeca', 'Bárbara', 'Eduarda', 'Sabrina', 'Heloísa', 'Letícia', 'Maya', 'Sara', 'Beatriz', 'Elisa', 'Isabel', 'Liz', 'Melissa', 'Sophie', 'Bianca', 'Emanuelly', 'Isabelly', 'Lorena', 'Milena', 'Stella', 'Bruna', 'Emily', 'Isadora', 'Luana', 'Mirela', 'Vitória', 'Yasmin']
    print('O nome feminino escolhido foi \033[4;35m{}\033[m.'.format(random.choice(f1)))
else:
#Lista de nomes para quem não sabe o sexo da criança.
    ns1 = ['Coralina', 'Martina', 'Adele', 'Ayla', 'Dora', 'Agnes', 'Julieta', 'Serena', 'Lia', 'Mia', 'Allana', 'Branca', 'Estrela', 'Linda', 'Micaela', 'Felipa', 'Naomi', 'Amora', 'Celina', 'Luna', 'Violeta', 'Analu', 'Charlote', 'Pérola', 'Angelina', 'Pietra','Ana Beatriz', 'Maria Eduarda', 'Ana Cecília', 'Maria Fernanda', 'Ana Clara', 'Maria Flor', 'Ana Júlia', 'Maria Helena', 'Ana Laura', 'Maria Íris', 'Ana Lívia', 'Maria Júlia', 'Ana Luiza', 'Maria Laura', 'Ana Sofia', 'Maria Luíza', 'Ana Vitória', 'Maria Sophia', 'Maria Alice', 'Maria Valentina', 'Maria Cecília', 'Maria Vitória', 'Maria Clara','Agatha', 'Camila', 'Esther', 'Isis', 'Maitê', 'Natália', 'Alícia', 'Carolina', 'Fernanda', 'Joana', 'Malu', 'Nicole', 'Amanda', 'Catarina', 'Gabriela', 'Laís', 'Maria', 'Olívia', 'Ana', 'Cecília', 'Gabrielly', 'Lara', 'Marian', 'Pietra', 'Antonela', 'Clara', 'Giovana', 'Larissa', 'Mariana', 'Rafaela', 'Aurora', 'Clarice', 'Júlia', 'Marina', 'Rebeca', 'Bárbara', 'Eduarda', 'Sabrina', 'Heloísa', 'Letícia', 'Maya', 'Sara', 'Beatriz', 'Elisa', 'Isabel', 'Liz', 'Melissa', 'Sophie', 'Bianca', 'Emanuelly', 'Isabelly', 'Lorena', 'Milena', 'Stella', 'Bruna', 'Emily', 'Isadora', 'Luana', 'Mirela', 'Vitória', 'Yasmin','Arthur Gabriel','João Vitor','Arthur Miguel','Luiz Felipe','Carlos Eduardo','Luiz Gustavo','Davi Luiz','Luiz Henrique','David Lucas','Davi Miguel','Enzo Gabriel','LuizOtávio','Enzo Miguel','Lucas Gabriel','João Gabriel','Pedro Henrique','João Guilherme','Pedro Lucas','João Lucas','Pedro Miguel','João Miguel','Vitor Hugo','João Pedro','Miguel', 'Davi', 'Gabriel', 'Arthur', 'Lucas', 'Matheus', 'Pedro', 'Guilherme','Alexandre','Eduardo','Henrique','Murilo','Theo','André','Enrico','Henry','Nathan','Thiago','Antônio','Enzo','Ian','Otávio','Thomas','Augusto','Erick','Isaac','Pietro','Vicente','Breno','Felipe','João','Rafael','Vinícius','Bruno','Fernando','Kaique','Raul','Vitor','Caio','Francisco','Leonardo','Rian','Yago','Cauã','Frederico','Luan','Ricardo','Ygor','Daniel','Guilherme','Lucas','Rodrigo','Yuri','Danilo','Gustavo','Mathias','Samuel']
    print('O nome aleatório escolhido foi \033[4;33m{}\033[m.'.format(random.choice(ns1)))