-- EXERCÍCIOS DE FIXAÇÃO DA AULA 13

-- 1. UMA LISTA COM AS PROFISSÕES DOS GAFANHOTOS E SEUS RESPECTIVOS QUANTITATIVOS

SELECT profissao, COUNT(nome) FROM gafanhotos
GROUP BY profissao
ORDER BY COUNT(nome);

-- 2. QUANTOS GAFANHOTOS E GAFANHOTAS NASCERAM APÓS 01/JAN/2005

SELECT sexo, COUNT(*) FROM gafanhotos
WHERE nascimento > '2005/01/01'
GROUP BY sexo;

-- 3. UMA LISTA COM OS GAFANHOTOS QUE NASCERAM FORA DO BRASIL, MOSTRANDO O PAÍS DE ORIGEM E O TOTAL DE PESSOAS NASCIDAS LÁ. SÓ NOS INTERESSAM OS PAÍSES QUE TIVEREM MAIS DE 3 GAFANHOTOS COM ESSA NACIONALIDADE

SELECT nacionalidade, COUNT(*) FROM gafanhotos
WHERE nacionalidade != 'BRASIL'
GROUP BY nacionalidade
HAVING COUNT(*) > 3;

-- 4. UMA LISTA AGRUPADA PELA ALTURA DOS GAFANHOTOS, MOSTRANDO QUANTAS PESSOAS PESAM MAIS DE 100KG E QUE ESTÃO ACIMA DA MÉDIA DE ALTURA DE TODOS OS CADASTRADOS

SELECT altura, COUNT(*) FROM gafanhotos
WHERE peso > 100 AND altura > (SELECT AVG(altura) FROM gafanhotos)
GROUP BY altura
ORDER BY COUNT(*);