-- EXERCÍCIOS PARA FIXAÇÃO

-- 1. UMA LISTA COM NOME DE TODAS AS 'GAFANHOTAS'

SELECT nome FROM gafanhotos
WHERE sexo = 'F'
ORDER BY nome;

-- 2. UMA LISTA COM OS DADOS DE TODAS AQUELES QUE NASCERA ENTRE 1/JAN/2000 E 31/DEZ/2015

SELECT * FROM gafanhotos
WHERE nascimento BETWEEN '2000-01-01' AND '2015-12-31'
ORDER BY nascimento;

-- 3. UMA LISTA COM O NOME DE TODOS OS HOMENS QUE TRABALHAM COMO PROGRAMADORES

SELECT nome, profissao FROM gafanhotos
WHERE profissao = 'programador' AND sexo = 'M'
ORDER BY nome;

-- 4. UMA LISTA COM OS DADOS DE TODAS AS MULHERES QUE NASCERAM NO BRASIL E QUE TÊM SEU NOME INICIADO COM A LETRA J

SELECT * FROM gafanhotos
WHERE nacionalidade = 'BRASIL' 
AND nome LIKE 'J%'
ORDER BY nome;

-- 5. UMA LISTA COM O NOME E NACIONALIDADE DE TODOS OS HOMENS QUE TÊM SILVA NO NOME, NÃO NASCERAM NO BRASIL E PESAM MENOS DE 100KG

SELECT nome, nacionalidade FROM gafanhotos
WHERE nome LIKE '%SILVA%'
AND nacionalidade != 'BRASIL'
AND sexo = 'M'
AND peso < 100
ORDER BY nacionalidade, nome;

-- 6. QUAL É A MAIOR ALTURA ENTRE OS GAFANHOTOS HOMENS QUE MORAM NO BRASIL?

SELECT MAX(altura) FROM gafanhotos
WHERE nacionalidade = 'BRASIL'
AND sexo = 'M';

-- 7. QUAL É A MEDIA DE PESO DOS GAFANHOTOS CADASTRADOS

SELECT AVG(PESO) FROM gafanhotos;

-- 8. QUAL O MENOR PESO ENTRE AS 'GAFANHOTAS' QUE NASCERAM FORA DO BRASIL E ENTRE 01/JAN/1990 E 31/DEZ/2000

SELECT MIN(peso) FROM gafanhotos
WHERE nacionalidade != 'BRASIL'
AND sexo = 'F'
AND nascimento BETWEEN '1990/01/01' AND '2000/12/31';

-- 9. QUANTAS 'GAFANHOTAS' TÊM MAIS DE 1.90 DE ALTURA

SELECT COUNT(*) FROM gafanhotos
WHERE altura > 1.9
AND sexo = 'F';
